name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Set up the environment to run tests

    steps:
    # Step 1: Check out the code from the repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Set the Python version to use

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    # Step 4: Run tests with pytest
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run pytest tests (adjust as needed)

    # Step 5: Save test results (optional)
    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: ./reports  # Adjust to your test results folder if needed
