name: Python CI

on:
  push:
    branches:
      - master  # Update branch to master
  pull_request:
    branches:
      - master  # Update branch to master

jobs:
  build:
    runs-on: ubuntu-latest  # Set up the environment to run tests

    steps:
    # Step 1: Check out the code from the repo
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8  # Set the Python version to use

    # Step 3: Cache Python dependencies (updated to v3)
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    # Step 5: Run tests with pytest
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run pytest tests (adjust as needed)

    # Step 6: Save test results (optional)
    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ./reports  # Adjust to your test results folder if needed
