name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to v4 (latest)

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5 (latest)
      with:
        python-version: 3.12.2

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt  # Force fresh install

    - name: Run tests
      run: |
        mkdir -p reports
        pytest --maxfail=1 --disable-warnings --junitxml=reports/results.xml

    - name: Upload test results as artifacts
      uses: actions/upload-artifact@v4  # Corrected to v4 (latest)
      with:
        name: test-results
        path: ./reports